name: Sync All Branches and Tags to Gitee/GitLab/Bitbucket

on:
  push:
    branches: ['**']  # 所有分支的推送触发
    tags: ['*']       # 所有标签的推送触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史（含所有分支和标签）

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_rsa_gitee
          echo "${{ secrets.GITLAB_PRIVATE_KEY }}" > ~/.ssh/id_rsa_gitlab
          echo "${{ secrets.BITBUCKET_PRIVATE_KEY }}" > ~/.ssh/id_rsa_bitbucket
          chmod 600 ~/.ssh/id_rsa_*
          # 配置多平台SSH密钥
          cat <<EOF > ~/.ssh/config
          Host gitee.com
            HostName gitee.com
            IdentityFile ~/.ssh/id_rsa_gitee
            User git
          Host gitlab.com
            HostName gitlab.com
            IdentityFile ~/.ssh/id_rsa_gitlab
            User git
          Host bitbucket.org
            HostName bitbucket.org
            IdentityFile ~/.ssh/id_rsa_bitbucket
            User git
          EOF
          ssh-keyscan gitee.com gitlab.com >> ~/.ssh/known_hosts

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Remotes
        run: |
          git remote add gitee git@gitee.com:flowstone/fs_base.git
          git remote add gitlab git@gitlab.com:flowstone/fs_base.git
          git remote add bitbucket git@bitbucket.org:flowstone/fs_base.git

      - name: Fetch All Branches and Tags
        run: |
          git fetch --prune origin
          git fetch --tags origin

      - name: Push to Gitee/GitLab/Bitbucket (All Branches and Tags)
        run: |
          # 推送所有分支和标签到 Gitee
          git push --all gitee --force
          git push --tags gitee --force
          # 推送所有分支和标签到 GitLab
          git push --all gitlab --force
          git push --tags gitlab --force
          # 推送所有分支和标签到 Bitbucket
          git push --all bitbucket --force
          git push --tags bitbucket --force