name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if Gitee repository exists
        id: check-repo
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITEE_TOKEN }}" \
            "https://gitee.com/api/v5/repos/${{ secrets.GITEE_USERNAME }}/target-repo-name")
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Gitee repository exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Gitee repository does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Gitee repository if not exists
        if: steps.check-repo.outputs.exists == 'false'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITEE_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://gitee.com/api/v5/user/repos" \
            -d '{"name": "target-repo-name", "private": false}'

      - name: Add Gitee remote
        run: |
          cd source
          git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_USERNAME }}/target-repo-name.git

      - name: Push to Gitee
        run: |
          cd source
          git push -u gitee main