name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if GitLab repository exists
        id: check-repo
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
            "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_NAMESPACE }}%2Ftarget-repo-name")
          if [ "$RESPONSE" -eq 200 ]; then
            echo "GitLab repository exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "GitLab repository does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitLab repository if not exists
        if: steps.check-repo.outputs.exists == 'false'
        run: |
          curl -X POST \
            -H "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
            "https://gitlab.com/api/v4/projects" \
            -d "name=target-repo-name&namespace_id=${{ secrets.GITLAB_NAMESPACE_ID }}"

      - name: Add GitLab remote
        run: |
          cd source
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_NAMESPACE }}/target-repo-name.git

      - name: Push to GitLab
        run: |
          cd source
          git push -u gitlab main